### ISSUE TITLE
Version: 6.0pre13, Build id: 211015-f5e4ca7a15 unable to build CoRE4INET

### ISSUE THREAD

**Issue by Chsuma09** [CoRE-RG/CoRE4INET#27] opened 2022-03-23 05:22 UTC
Hi 

I am trying to build Core4INET but unsuccessful with the environment I have. Unable to debug further.

Omnet Version: 6.0pre13, Build id: 211015-f5e4ca7a15
inet version : 4.2
inet commit id: 676711aa40a7cfd495f2afb9136a0562cf8cb871

type of error:
**dependencies_makefrag:16: *** "INETs IPv4 feature is required for CORE4INETs IPoRE feature, but it is not enabled. Enable IPv4 or disable IPoRE. See INSTALL file for details.".  Stop.
make[1]: Leaving directory '/hdd/Projects/EmbedUR/Molex/CoRE4INET/src'
make: *** [Makefile:2: all] Error 2**

in inet I have already enabled IPv4.

your help and support is greatly appreciated.!!

Rgds
Chandra

**Comment by THaeckel** [comment] 2022-03-23 10:31
Hello Chandra

we have not yet switched to OMNeT 6 since it has not been finally released. Also, CoRE4INET uses inet version 3.6.6 and is not compatible to INET 4. 

Check out the installation instructions in the Readme:
Download OMNeT++ 5.5.1 https://omnetpp.org/download/
Install OMNeT++ https://doc.omnetpp.org/omnetpp/InstallGuide.pdf
Get INET framework 3.6.6 https://inet.omnetpp.org/Download.html or clone it from https://github.com/inet-framework/inet/releases/tag/v3.6.6

Best regards
Timo

**Comment by Chsuma09** [comment] 2022-04-04 07:03
Hi Timo,

We dowlaoded as per the suggestion, but still unable to build the CORE4INET. Below is the error,

**make[1]: Entering directory '/hdd/Projects/EmbedUR/Molex/CoRE4INET/src'
core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICM.cc
core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICMStates.cc
core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICMStates.cc
core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICM.cc
In file included from core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICMStates.cc:23:
In file included from core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICMStates.h:26:
core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICMState.h:35:10: fatal error: 'core4inet/scheduler/CoRE4INET_TTEScheduler.h' file not found
#include "core4inet/scheduler/CoRE4INET_TTEScheduler.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICM.cc:25:
In file included from core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICM.h:30:
In file included from core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICMStateContex.h:30:
core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICMState.h:33:10: fatal error: 'core4inet/TTEScheduler.h' file not found
#include "core4inet/TTEScheduler.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:280: ../out/clang-debug/src/core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICM.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICMStates.cc:23:
In file included from core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICMStates.h:28:
core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICMState.h:33:10: fatal error: 'core4inet/TTEScheduler.h' file not found
#include "core4inet/TTEScheduler.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:280: ../out/clang-debug/src/core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICMStates.o] Error 1
In file included from core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICM.cc:24:
In file included from core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICM.h:30:
In file included from core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICMStateContex.h:26:
core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICMState.h:35:10: fatal error: 'core4inet/scheduler/CoRE4INET_TTEScheduler.h' file not found
#include "core4inet/scheduler/CoRE4INET_TTEScheduler.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:280: ../out/clang-debug/src/core4inet/synchronisation/AS6802/HICompressionMaster/CoRE4INET_HICM.o] Error 1
1 error generated.
make[1]: Leaving directory '/hdd/Projects/EmbedUR/Molex/CoRE4INET/src'
make[1]: *** [Makefile:280: ../out/clang-debug/src/core4inet/synchronisation/AS6802/SICompressionMaster/CoRE4INET_SICMStates.o] Error 1
make: *** [Makefile:2: all] Error 2
"make MODE=debug -j4 all" terminated with exit code 2. Build might be incomplete.

12:30:49 Build Failed. 10 errors, 0 warnings. (took 3s.394ms)**

Rgds
Chandra

**Comment by THaeckel** [comment] 2022-04-04 07:23
Hi Chandra,
this seams to be a Duplicate of #7, please check out the replies of Philipp over there. 

Regards,
Timo

**Comment by Chsuma09** [comment] 2022-04-05 06:42
Thanks it resolved the issue..

**Closed** 2022-04-05 07:07 UTC
Labels: question
