### ISSUE TITLE
bug when more listeners in one node | priority 6

### ISSUE THREAD

**Issue by renemarcker** [CoRE-RG/CoRE4INET#6] opened 2019-12-12 10:09 UTC
Hi CoRE-RG group,

I have been working with your Qbv example. I have observed two issues:

1) I have a node containing BE listener as application 0 and a Q listener as application 1. The issue is when look at the data in the scalar. The expected count frame is 400 for BE and 40000 for Q, but the application 0 have count of 40400 and the application 1 have count of 40000. So like the the data go though the application 0 before reaching application 1. 

2) I have a Q talker with priority 6, but when I look in the data, non data is registered at the listener. I have tried with total open gatecontrol and no different result. There are no problem when changing to a different priority.

Maybe some bugs or I'm doing some wrong

**Comment by THaeckel** [comment] 2019-12-12 10:48
Dear renemarcker,

if you can provide me with an example network where I can see the unexpected behavior you describe I will check if there is a bug. For now, I can answer your questions as follows:

1. BE listeners, as well as Q listener applications (sinks), receive their traffic via the same input queue, the beIn queue. This is due to other protocol implementations running on the same host as standard ethernet apps, e.g. AS6802 and AVB. All incoming best-effort frames are duplicated in the beIn queue and forwarded to all sinks (BE and Q). The applications filter the incoming messages according to the configuration. BE-sinks only filter according to the specified MAC addresses, Q-sinks filter according to the specified MAC addresses, VLANs and Q-priority. Thus the count works as expected. If you would like different behavior, try using Q-sinks/sources only in your network and use priority 0 for best-effort traffic.

2. We have never encountered any issues with certain priorities not being received. Maybe there is an error in the configuration of the VLANs or Q-sink apps, maybe there is a Qbv gate closed in some switch or host. You can try to use a BE-sink to check if any frames arrive at the beIn queues or check in the simulations where the frames are dropped.

I hope this helps. Feel free to add other questions or an example so I can check out if there is a bug.
Best,
Timo

**Closed** 2019-12-20 12:05 UTC
Labels: question
